# Generated by Django 3.2.6 on 2021-09-12 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MstTestStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name_kanji', models.CharField(max_length=100)),
                ('name_hira', models.CharField(max_length=100)),
                ('name_kata', models.CharField(max_length=100)),
                ('first_letter', models.CharField(max_length=1)),
                ('last_letter', models.CharField(max_length=1)),
                ('is_ends_n', models.BooleanField()),
                ('city_name', models.CharField(max_length=100)),
                ('jr_co_name', models.CharField(max_length=100)),
                ('rail_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('prf_no', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('prf_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_letter', models.CharField(max_length=1)),
                ('goal_letter', models.CharField(max_length=1)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_finished', models.BooleanField(default=False)),
                ('goal_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goal_staion', to='stapp.mstteststation')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start_staion', to='stapp.mstteststation')),
            ],
        ),
        migrations.CreateModel(
            name='TestChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stapp.testgame')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stapp.mstteststation')),
            ],
        ),
        migrations.AddField(
            model_name='mstteststation',
            name='prf_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stapp.prefecture'),
        ),
    ]
