# Generated by Django 3.2.6 on 2021-08-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefecture',
            name='prf_no',
            field=models.IntegerField(default=0),
        ),
    ]
